language: c # not really, but using make
dist: trusty # has a newer version of pandoc

addons:
  apt:
    packages:
      pandoc
      texlive

script:
  make all

deploy:
  provider: releases
  api_key:
    secure: $GH_TOKEN
  file_glob: true
  file: out/*
  skip_cleanup: true
  on:
    tags: true
