language: c # not really, but using make
sudo: required

before_install:
  - wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-1.19.2.1-1-amd64.deb

addons:
  apt:
    packages:
      texlive
      lmodern

script:
  make all

deploy:
  provider: releases
  api_key:
    secure: $GH_TOKEN
  file_glob: true
  file: out/*
  skip_cleanup: true
  on:
    tags: true
